[workspace]
resolver = "3"
members = ["crates/gezik-core", "crates/gezik-config", "crates/gezik-platform", "crates/gezik"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"

[workspace.dependencies]
gezik-core = { path = "crates/gezik-core" }
gezik-config = { path = "crates/gezik-config" }
gezik-platform = { path = "crates/gezik-platform" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
